name: FMD-CI

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: make application-common.yaml
        run: |
          cd ./src/main/resources
          touch ./application-common.yaml
          echo "${{ secrets.APPLICATION_COMMON}}" > ./application-common.yaml

      - name: make application-prod.yaml
        if: contains(github.base_ref, 'main')
        run: |
          cd ./src/main/resources
          touch ./application-prod.yaml
          echo "${{ secrets.APPLICATION_PROD}}" > ./application-prod.yaml

      - name: make application-dev.yaml
        if: contains(github.base_ref, 'develop')
        run: |
          cd ./src/main/resources
          touch ./application-dev.yaml
          echo "${{ secrets.APPLICATION_DEV}}" > ./application-dev.yaml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build & push to prod
        if: contains(github.base_ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-prod -t ${{ secrets.DOCKER_USERNAME }}/fmd-prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/fmd-prod

      - name: Docker build & push to dev
        if: contains(github.base_ref, 'develop')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-dev -t ${{ secrets.DOCKER_USERNAME }}/fmd-dev:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fmd-dev:latest
